### ISSUE TITLE
Release as a Craft3/4 plugin?

### ISSUE THREAD

**Issue by johndwells** [simplicate-web/redactor-link-styles#2]
Great job on the javascript implementation! I was able to successfully integrate it into a project, works like a charm.

However it's a shame this hasn't been built as a plugin, so that others can install it easily.

Would you be interested in a PR that provides this, are you interested in maintaining a fully-fledged plugin?

If not, would you be comfortable if I released a plugin that leveraged your JS? I'd happily give you credit and keep it OS.

**Comment by nevsie** [comment]
Used and implemented successfully as well.
I would be keen to see this as a plugin also.

**Comment by stevecomrie** [comment]
Hey John,

Sorry for the late reply.

I'm rather hesitant to package this up as a Craft CMS plugin, at least in its current state.

This is just a single file that gets dropped into `cms/config/redactor/plugins` and then it _just works_.

It's not the only Redactor plugin out there, plenty of others exist both inside and outside of the Craft ecosystem.

While I don't want to tell anyone what they should learn and where they should focus their time, I do think that understanding how to edit Redactor config files is an important part of managing a Craft site -- particularly if the sites you build use Redactor heavily.

If there was some added benefit (outside of findability through the plugin store) or new functionality that you thought converting this to a plugin might provide to users, then I'd consider it, otherwise, I think I'd prefer to leave it as is.

**Comment by mark-chief** [comment]
-- deleted. Solved my issue. Thanks

**Comment by johndwells** [comment]
I don't know why, but I didn't know that the plugin could be installed by dropping the js into `config/redactor/plugins`! So I retract my suggestion to bundle this into a Craft plugin, you're right it'd serve no greater purpose to do so, and there are already other well-known and well-built plugins that can help with any missing pieces (such as CP CSS to inject some styles into the CP to match your custom link classes).

Thanks again for this, it's a staple in our projects!
